apiVersion: 1

datasources:
  - name: $GRAFANA_DATASOURCE_NAME
    uid: dmr-elasticsearch
    type: elasticsearch
    access: proxy
    url: $ELASTICSEARCH_URL
    isDefault: true
    editable: true
    jsonData:
      index: $ES_INDEX
      interval: ""
      timeField: KoeretoejOplysningGrundStruktur.KoeretoejOplysningFoersteRegistreringDato
      tlsSkipVerify: $ELASTICSEARCH_INSECURE
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: ApiKey $ELASTICSEARCH_API_KEY
